### ISSUE TITLE
win10 无法自动启动

### ISSUE THREAD

**Issue by appleatiger** [dfdragon/kcptun_gclient#1]

**Comment by dfdragon** [comment]
程序没有请求UAC，所以点击“程序开机自启”需要以系统管理员权限运行才能写入注册表。

**Comment by appleatiger** [comment]
使用管理员权限依然是报错误

**Comment by dfdragon** [comment]
我自己用的就是win10 64位。你那边报什么错？

**Comment by bcdong** [comment]
![default](https://cloud.githubusercontent.com/assets/14255979/18678501/d63ba228-7f8e-11e6-902f-a52783ea3640.png)
请问为什么我点了启动以后控制台显示begin后就立刻显示end了?

**Comment by dfdragon** [comment]
你改过客户端的文件名吗？默认的文件名应该是client_windows_386.exe或者client_windows_amd64.exe吧，你这里怎么显示的是client_windows_kcptun.exe，确认下配置的KCPTun客户端exe文件是否正确。

**Comment by bcdong** [comment]
我解决了，是kcptun版本问题，谢谢！
