### ISSUE TITLE
你好，关于模式选择的问题……

### ISSUE THREAD

**Issue by fa6ca** [dfdragon/kcptun_gclient#10]
我是个纯小白，麻烦问下如果在服务器端安装的时候用的是fast3，那么在配置工具中如果选择其他比如fast1，那么实际运行模式是以哪个为主呢？ ……

是否需要客户端和服务端模式选择保持一致呢？谢谢……

请问是不是部署服务器的时候如果选择了fast3，那么KCP配置客户端可以选择任意一种加速模式运行？并且有效。如果配置服务器的时候选择了fast2，那么KCP配置客户端最高只能使用FAST2模式，及时选择fast3，也是运行在fast2模式上，不知道是不是这样？求指教，谢谢……

**Comment by dfdragon** [comment]
模式不需要客户端和服务端保持一致，各管各的。

cnonez <notifications@github.com>于2016年11月26日周六 22:56写道：
