### ISSUE TITLE
偶尔会有不激活窗口问题

### ISSUE THREAD

**Issue by yjd** [dfdragon/kcptun_gclient#11]
就是缩到托盘里。点击的时候底下任务栏有标题。但是整个窗口没激活=最小化窗口的状态

**Comment by dfdragon** [comment]
这是windows 2000之后的一个特性，默认不干扰其它手动激活的窗口。新的commit已经修改，点击托盘图标后前台显示。

**Comment by yjd** [comment]
收到。谢了
