### ISSUE TITLE
不加上编译好的下载链接?

### ISSUE THREAD

**Issue by ghost** [dfdragon/kcptun_gclient#12]

**Comment by ghost** [comment]
最新版本好像没有编译..另外右下角版本显示错误不知道修复没有

**Comment by dfdragon** [comment]
只是一些微小的改动，所以没有发布编译。右下角的说明可能引起歧义了，我的本意是想说这个GUI里的参数是依据kcptun的某一版本定义的，也是能支持的kcptun的最低版本。

**Comment by dfdragon** [comment]
1.0.14版本发布，部分说明文字已改动。
