### ISSUE TITLE
能够只监听本地环路(127.0.0.1)吗?

### ISSUE THREAD

**Issue by Comaxim** [dfdragon/kcptun_gclient#13]
设置里只有本地侦听端口选项，没有本地地址选项。每次都监听任意地址了(例如:":1080",希望能够“127.0.0.1:1080”)。

**Comment by dfdragon** [comment]
这个参数是直接用的kcptun作者所给的格式，默认允许来自局域网的连接，我加个选项吧。

**Comment by dfdragon** [comment]
新的1.0.14版本加入了是否只允许本机连接选项。
