### ISSUE TITLE
不能调整窗口大小

### ISSUE THREAD

**Issue by willww64** [dfdragon/kcptun_gclient#14]
窗口有点大，最下方被任务栏挡住了，不能调整窗口大小，可否考虑加上调整功能？

**Comment by dfdragon** [comment]
你现在用的屏幕分辨率是多少？

**Comment by willww64** [comment]
1920x1080  windows10 1607

**Comment by dfdragon** [comment]
和我用的分辨率是一致的。这么大会显示不全吗？程序窗口的大小才是1194×717啊

**Comment by willww64** [comment]
我截了图，不知道怎么能发给你。

**Comment by dfdragon** [comment]
评论可以发截图的，把图片拖进来。不过如果你用的分辨率是1920x1080的话，应该可以完全显示程序窗口的，你查一下windows里的显示设置，看是不是调整显示百分比了。
![1](https://cloud.githubusercontent.com/assets/9766935/21287664/f8da1f82-c4ab-11e6-9262-f2d67013e12b.png)

**Comment by willww64** [comment]
找到原因了，显示设置里更改文本、应用和其他项目的大小系统默认的是 150%。改成 100% 就好了，不过字就太小了。

**Comment by willww64** [comment]
嗯嗯，是这样的，好久没用 windows 了，不熟悉了。非常感谢你写的工具！

**Comment by willww64** [comment]
我真是渣渣，编辑框下面的 `Attach files by dragging & dropping`，被我华丽丽地忽视了。。。真不好意思耽误了你时间。

**Comment by dfdragon** [comment]
：）太客气了，这本来就是个互相交流和学习的平台。
