### ISSUE TITLE
程序崩溃了一次后无法启动了

### ISSUE THREAD

**Issue by songkeys** [dfdragon/kcptun_gclient#15]
第一次用是好的，Windows客户端崩溃闪退后，重启程序，点启动，日志如下：

执行命令："C:\Users\songkeys\Desktop\VPS\Kcptun\client_windows_amd64.exe" -c "C:\Users\songkeys\Desktop\VPS\Kcptun\config.txt"
*************************** begin ***************************
2017/01/13 09:09:49 version: 20170112
2017/01/13 09:09:49 listen tcp :443: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
**************************** end ****************************

重启了VPS还是这个问题。是什么原因呢，小白不懂，求教了。

**Comment by dfdragon** [comment]
从提示看，说的是443端口已经被另外的程序占用了，检查一下是不是启用了多个kcptun进程，并且不止一个进程使用了443端口。
另外，你使用的是client_windows_amd64.exe，不需要重启vps的，或者换句话说，vps应该使用kcptun的服务端程序

**Comment by songkeys** [comment]
我也在windows上结束进程试了很多遍还是一样，刚刚重启了就可以了。估计是崩溃的程序没彻底结束掉吧。
十分感谢！
