### ISSUE TITLE
开机自启找不到相对路径的配置文件

### ISSUE THREAD

**Issue by cd-rom** [dfdragon/kcptun_gclient#17]
执行命令："client_windows_386.exe" -c "config.json"
*************************** begin ***************************
2017/01/21 08:57:13 open config.json: The system cannot find the file specified.
**************************** end ****************************

开机自启找不到相对路径的配置文件，关掉程序后，重新打开才可以

**Comment by dfdragon** [comment]
新发布了1.0.17版，试一下这个版本。

**Comment by cd-rom** [comment]
可以了
