### ISSUE TITLE
建议加上二维码传递，并标准化参数传递

### ISSUE THREAD

**Issue by Justsoos** [dfdragon/kcptun_gclient#18]
1，二维码传递这么多，这么复杂参数，url，是必然的。如同ss
2，url标准化，比如用kcptun://BASE64_URL_PARAMETER

这样一来，这个gui 还能开源到手机，pc，并作为标准传播出去

**Comment by dfdragon** [comment]
多谢你的建议，我会考虑一下看如何处理。
