### ISSUE TITLE
能否查下版本1.0.17

### ISSUE THREAD

**Issue by five927** [dfdragon/kcptun_gclient#19]
请问卡巴对1.0.17总是报病毒，无法下载，之前的1.0.13就没问题，能帮忙看下吗

**Comment by dfdragon** [comment]
呃，这个我没什么好办法。我把15到17这三个版本查了一下，15没报，16有一个杀毒引擎报，17有三个引擎报。17版本的结果具体可看[这里](https://www.virustotal.com/zh-cn/file/e87003bd19ad98e8dd235d1a9d33ec6be9d6200e3f7c9e5684926affa10bddd0/analysis/1485685670/)。如果你信任这个软件的话，我只能建议你先关闭杀软再下载或使用15版本（16版本卡巴报了）。15版本和17版本的区别不大，不会影响使用的。

**Comment by five927** [comment]
好的，多谢了
