### ISSUE TITLE
 希望增加断线重连功能

### ISSUE THREAD

**Issue by ghost** [dfdragon/kcptun_gclient#2]
开机启动，网络如果不好，就连不上，软件又没有自动重连功能。

···
执行命令："D:\kcptun\client_windows_386.exe" -l :7878 -r xxx.xxx.xxx -key "" -crypt xor -nocomp -conn 6
**************************\* begin ***************************
2016/09/24 05:06:57 version: 20160922
2016/09/24 05:06:58 listening on: [::]:7878
2016/09/24 05:06:58 encryption: xor
2016/09/24 05:06:58 nodelay parameters: 0 20 2 1
2016/09/24 05:06:58 remote address: xxx.xxx.xxx.xx:xxx
2016/09/24 05:06:58 sndwnd: 128 rcvwnd: 1024
2016/09/24 05:06:58 compression: false
2016/09/24 05:06:58 mtu: 1350
2016/09/24 05:06:58 datashard: 10 parityshard: 3
2016/09/24 05:06:58 acknodelay: false
2016/09/24 05:06:58 dscp: 0
2016/09/24 05:06:58 sockbuf: 4194304
2016/09/24 05:06:58 keepalive: 10
2016/09/24 05:06:58 conn: 6
2016/09/24 05:06:58 autoexpire: 0
2016/09/24 05:06:58 dial udp xxx.xxx.xxx.xxx:xxx: connect: A socket operation was attempted to an unreachable network.
net.DialUDP
github.com/xtaci/kcp-go.DialWithOptions
    /Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:882
main.main.func1.1
    /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:314
main.main.func1
    /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:366
runtime.call16
    /usr/local/go/src/runtime/asm_386.s:498
reflect.Value.call
    /usr/local/go/src/reflect/value.go:434
reflect.Value.Call
    /usr/local/go/src/reflect/value.go:302
github.com/urfave/cli.HandleAction
    /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:487
github.com/urfave/cli.(_App).Run
    /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:245
main.main
    /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:406
runtime.main
    /usr/local/go/src/runtime/proc.go:183
runtime.goexit
    /usr/local/go/src/runtime/asm_386.s:1612
createConn()
main.main.func1.1
    /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:316
main.main.func1
    /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:366
runtime.call16
    /usr/local/go/src/runtime/asm_386.s:498
reflect.Value.call
    /usr/local/go/src/reflect/value.go:434
reflect.Value.Call
    /usr/local/go/src/reflect/value.go:302
github.com/urfave/cli.HandleAction
    /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:487
github.com/urfave/cli.(_App).Run
    /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:245
main.main
    /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:406
runtime.main
    /usr/local/go/src/runtime/proc.go:183
runtime.goexit
    /usr/local/go/src/runtime/asm_386.s:1612
***************************\* end ****************************
···

**Comment by dfdragon** [comment]
做自动重连的主要问题在于：我这边只是知道kcptun发生异常退出了，但不知道怎样判断是由于参数配置错误发生异常还是其它的什么原因，如果能区分出异常类型的话，倒是可以尝试重连。或者我匹配输出的字符串试一下

**Comment by dfdragon** [comment]
我刚看到的，不是v20160919已经修复这个问题了吗？

**Comment by ghost** [comment]
可以提供一个选项：断线重连
允许在异常退出后自动尝试重新连接。

这样就可以满足我的使用场景了。

**Comment by dfdragon** [comment]
好的，这个功能在下一版加上。这两天一直在折腾osx下捕获控制台输出的问题，没顾上

**Comment by ghost** [comment]
Thanks

**Comment by dfdragon** [comment]
新版已发布，你试一下
