### ISSUE TITLE
基础参数应该怎么设置？

### ISSUE THREAD

**Issue by FengkuiChan** [dfdragon/kcptun_gclient#21]
本地侦听端口、KCP服务器地址及端口应该怎么填？
我的shadowsocks服务器端口是443，本地代理端口是1080；kcptun服务器端口是8399。

**Comment by dfdragon** [comment]
参考#6、#7

**Comment by FengkuiChan** [comment]
@dfdragon 
#6 , #7 都看过了，还是有疑问。在#7引用的文章：https://blog.kuoruan.com/102.html 中，有个截图，他填写Kcptun服务器地址是127.0.0.1，这对吗？
我这样填：
本地侦听端口填ss的端口443；
KCP服务器地址填ss的ip；
KCP服务器端口填8399.
但是，好像没有加速效果。是不是本地侦听端口填错了，应该填1080，抑或因为其他原因？谢谢。

**Comment by dfdragon** [comment]
“KCP服务器地址填ss的ip；
KCP服务器端口填8399. ”——这个是正确的。

kcptun的本地侦听端口是可以用任意一个**未被占用**的端口，Shadowsocks客户端需要连接这个端口。

配置ss+kcptun有点绕，里面涉及的端口多，你弄懂下面的图就清楚了。

浏览器或其它<——>(ss侦听端口)Shadowsocks客户端<——>(kcptun本地侦听端口)kcptun客户端<<————————>>(kcptun端口)kcptun服务端<——>(ss端口)Shadowsocks服务端
