### ISSUE TITLE
关于软件的图标

### ISSUE THREAD

**Issue by icecrack** [dfdragon/kcptun_gclient#22]
首先谢谢你的作品,用起来很顺手,而且更新也挺勤,功能在不断的完善. 但是这个图标,不知道是不是你设计出来的,如果只是随意找了一个图标的话,是否可以考虑下使用KcpTun的官方图标?
[
![image](https://cloud.githubusercontent.com/assets/1057875/23337085/f1154b7e-fc1d-11e6-80a6-8885419e465d.png)
](url)

**Comment by dfdragon** [comment]
据我所知另一个kcptun的管理客户端使用了这个图标，现在我再使用这个有点不合适了。不管怎样，都谢谢你的提议。
