### ISSUE TITLE
1.1.1 版本CPU占用过高

### ISSUE THREAD

**Issue by nsb2006** [dfdragon/kcptun_gclient#23]
i5 4200M，走代理时kcptun_gclient.exe CPU占用20%+，没有代理流量时正常，以前版本没注意过是否存在此问题。
系统：Win 7 Ultimate x64.

**Comment by dfdragon** [comment]
我在自己的win7和win10下都没有发现这个问题。理论上说，本程序只是启动kcptun客户端的一个实例，然后开了读写管道读实例的控制台输出而已，不会很占用cpu资源的。你提到的占用20%以上肯定是不正常的，换个机子试一下看能否复现。

**Comment by nsb2006** [comment]
重启机器后不再复现，应该是系统问题，感谢答复。

**Comment by Amaterasu33** [comment]
i5-4210H同样发现占用cpu过高的问题（占用率25%左右，频率最高，应该是单线程满载了），且是否占用过高的CPU与是否有代理流量无关，暂时未发现规律...重启无法解决。
系统Win10 Creator Update x64

**Comment by dfdragon** [comment]
再观察一下吧，我这边无法复现，也极少人报告这个问题。你的CPU是4线程的？你进任务管理器看一下是kcptun_gclient.exe占用CPU还是client_windows_amd64.exe占用CPU @Amaterasu33

**Comment by Amaterasu33** [comment]
是kcptun_gclient.exe。我再观察一下吧，现在还没发现什么规律，会突然高占用一段时间然后恢复正常

**Comment by Doflatango** [comment]
这个问题是因为系统进程里面已经有一个 kcp client，所以 kcptun_gclient 去尝试启动一个 kcp  client 的时候因为端口被占用总是失败，然后一直在重启-失败-重启循环，导致 cpu 占用一下就高了。

已经存在的那个  kcp client 是由 kcptun_gclient 启动的，至于为什么会被 kcptun_gclient 忽略掉，可能是个 bug？
