### ISSUE TITLE
请问后台那个叫做我的专属激励师的窗口有什么作用

### ISSUE THREAD

**Issue by 0x7A2C9E5D** [dfdragon/kcptun_gclient#24]
请问后台那个叫做我的专属激励师的窗口有什么作用，看着怪挂的，感觉像广告，如果有广告请放到主界面上，并说明一下，不然感觉很可疑

**Comment by dfdragon** [comment]
程序的一个小彩蛋而已。我养的喵，马路旁树根下捡的，中华田园猫，快九岁了：)

ssc19940105 <notifications@github.com>于2017年3月24日周五 19:37写道：

**Comment by ssc19940105** [comment]
可以放个图吗

**Comment by bd67625** [comment]
很喜欢这个软件 :+1:

**Comment by dfdragon** [comment]
:smiley: 代表我家猫谢谢你啊 :smiley_cat:
