### ISSUE TITLE
UAC提权功能能不能去掉．现在无法开机自启动了

### ISSUE THREAD

**Issue by ghost** [dfdragon/kcptun_gclient#3]
系统windows 10
UAC提权功能能不能去掉．现在无法开机自启动了
上一个版本还可以启动．
现在无法自动启动了．不管是软件自带的开机启动，还是自己shell:startup添加的启动项目，都无法正常工作

**Comment by dfdragon** [comment]
正在外出差，这几天无法改代码。你用的win10具体的版本号告知一下。另外，现在换到前一个版本使用注册表方式能正常开机启动吗？加UAC提权就是为了操作注册表用的，我自用的win10环境没出现过这个问题。

2016年10月11日 12:54，"netroby" notifications@github.com写道：

**Comment by kawashiro310** [comment]
同感最好去掉UAC，这样能开机静默启动，可以放到这个目录里面
C:\Users<User>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by dfdragon** [comment]
如果UAC使用有问题的话，请告知Windows详细版本号信息并尽可能详细描述一下现象，我自用的win10一直使用正常。一般来说，UAC提权的提示在第一次选择确认后就不会再次出现了，我不知道是不是Windows更新了安全策略，所以需要os详细版本号和我的比对一下。

2016年10月12日 20:01，"kawashiro310" notifications@github.com写道：

**Comment by ghost** [comment]
windows 10 14393.222

**Comment by ghost** [comment]
我把系统UAC调到最低都不行。

**Comment by choicky** [comment]
之前的版本能开机自动运行；v1.0.12 在我两台win10上同样无法开机启动。

手工双击运行时，会有一个窗口问是否同意运行。

win10，专业版64位，10586。

**Comment by dfdragon** [comment]
挺奇怪的，我这边也是14393.222，win10 x64 专业版，但两台电脑都没有问题，具体原因未知。

新发布了一个版本，去除UAC提权功能。

**Comment by dfdragon** [comment]
刚装完系统更新，14393.321也没有出现问题。

**Comment by choicky** [comment]
多谢更新

**Comment by ghost** [comment]
测试可以了. 谢谢Repo主更新Fix
