### ISSUE TITLE
期待Mac版本，谢谢！

### ISSUE THREAD

**Issue by zky999** [dfdragon/kcptun_gclient#5]
期待Mac版本，谢谢！

祝好！

**Comment by dfdragon** [comment]
mac版本已经发布过一版，在[这里](https://github.com/dfdragon/kcptun_xclient/releases)

**Comment by dfdragon** [comment]
由于一些原因，windows版和mac版是分开的，后期会考虑合并。

**Comment by zky999** [comment]
貌似这个mac也是字符界面的？官方已有mac版的字符界面客户端了哦。另外您的这个客户端在macOS sierra 10.12中报错不能运行。

**Comment by zky999** [comment]
MacBook-Pro:Downloads User$ ./kcptun_xclient
dyld: Library not loaded: @rpath/libcgunwind.1.0.dylib
  Referenced from: /Users/User/Downloads/./kcptun_xclient
  Reason: image not found
Abort trap: 6

**Comment by dfdragon** [comment]
[libcgunwind.1.0.zip](https://github.com/dfdragon/kcptun_gclient/files/532555/libcgunwind.1.0.zip)

我上传了一个libcgunwind.1.0.dylib，你解压缩后把它和kcptun_xclient放在同一目录中试一下。

**Comment by zky999** [comment]
有了libcgunwind.1.0.dylib之后也报错：

MacBook-Pro:Downloads User$ ./kcptun_xclient
Exception EAccessViolation in module kcptun_xclient at 00034A67.
Access violation at address 944EB682, accessing address 00000000.

**Comment by dfdragon** [comment]
我是在VMware里 OS X EI Capitan 10.11.6 下做的测试。你看一下这个文件：“/usr/lib/libc.dylib” 是否存在

**Comment by zky999** [comment]
该文件在我的系统里存在：
MacBook-Pro:Downloads User$ find /usr/lib -iname 'libc.dylib'
/usr/lib/libc.dylib

**Comment by dfdragon** [comment]
我先试试装一个macOS sierra 10.12内测吧，感谢你的反馈。

**Comment by zky999** [comment]
好的，感谢您的辛苦工作！

另外也可以确定这个程序所需要加载的其他库也存在：
MacBook-Pro:Downloads User$ otool -L kcptun_xclient
kcptun_xclient:
    @rpath/libcgunwind.1.0.dylib (compatibility version 0.0.0, current version 0.0.0)
    /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libiconv.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libdl.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libpthread.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libc.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libSystem.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libobjc.dylib (compatibility version 0.0.0, current version 0.0.0)
    /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/CoreGraphics (compatibility version 0.0.0, current version 0.0.0)
    /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ImageIO.framework/ImageIO (compatibility version 0.0.0, current version 0.0.0)
    /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreText.framework/CoreText (compatibility version 0.0.0, current version 0.0.0)
    /System/Library/Frameworks/ApplicationServices.framework/Frameworks/PrintCore.framework/PrintCore (compatibility version 0.0.0, current version 0.0.0)

MacBook-Pro:Downloads User$ otool -L kcptun_xclient |awk -F '(' '{print $1}' |while read f; do [[ -f "$f" ]] && printf "%s\t OK\n" "$f" || printf "%s\t Failed\n" "$f"; done
kcptun_xclient:  Failed
@rpath/libcgunwind.1.0.dylib     Failed
/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation   OK
/usr/lib/libiconv.dylib  OK
/usr/lib/libdl.dylib     OK
/usr/lib/libpthread.dylib    OK
/usr/lib/libc.dylib  OK
/usr/lib/libSystem.dylib     OK
/usr/lib/libobjc.dylib   OK
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/CoreGraphics  OK
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/ImageIO.framework/ImageIO    OK
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreText.framework/CoreText  OK
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/PrintCore.framework/PrintCore    OK

**Comment by dfdragon** [comment]
是我打包时出了问题，现在已重新发布[v1.0.0](https://github.com/dfdragon/kcptun_xclient/releases/tag/v1.0.0)
