### ISSUE TITLE
求改软件详细使用方式

### ISSUE THREAD

**Issue by free3nvy** [dfdragon/kcptun_gclient#6]

**Comment by dfdragon** [comment]
这个windows客户端只是kcptun的图形化配置管理界面，你还需要原版的kcptun([项目下载地址](https://github.com/xtaci/kcptun/releases))，建议你参考一下[这篇文章](http://www.8dlive.com/post/371.html)。如果对参数配置有什么疑问的话，可以去[这里](https://github.com/xtaci/kcptun/issues)搜索或提问。
