### ISSUE TITLE
如何配合Shadowsocks使用

### ISSUE THREAD

**Issue by rieval** [dfdragon/kcptun_gclient#7]
Shadowsocks客户端的本地端口为127.0.0.1:1080
请问我该如何设置才能使Kcptun监听Shadowsocks客户端的端口，然后Proxifier监听kcptun端口实现翻墙的效果呢？

**Comment by dfdragon** [comment]
根据你的描述，我猜测你可能弄混了，kcptun应该在最后一层：

浏览器或其它<——>Proxifier<——>Shadowsocks客户端<——>kcptun客户端<<————————>>kcptun服务端<——>Shadowsocks服务端。

可以参考一下这篇[文章](https://blog.kuoruan.com/102.html)

**Comment by rieval** [comment]
感谢！
的确是我搞混了，已经成功解决。
