### ISSUE TITLE
连接时断时续是正常么

### ISSUE THREAD

**Issue by hwk603** [dfdragon/kcptun_gclient#8]
![images 2016-11-13 1478970274](https://cloud.githubusercontent.com/assets/7033138/20239730/4d2046aa-a942-11e6-8003-09fd2a32ca1b.png)

**Comment by hwk603** [comment]
实测，加速效果挺明显的，Youtube 视频的 connection speed 由几百k增加到2000+k。

![images 2016-11-13 1478970427](https://cloud.githubusercontent.com/assets/7033138/20239747/9d35d1be-a942-11e6-93d2-1b11f2bbc17a.png)

但是我看到其他人用 fast2 模式的加速，可以达到上万k，所以怀疑是不是配置有问题，然后就发现 kcp 客户端的连接总是时断时续，会不会是因此才不能达到最快加速？

谢谢。

**Comment by dfdragon** [comment]
从日志看问题不大，你所说的“时断时续”是正常的。关于配置参数的问题，内置的模式只是一个可选项，但不是最优项，它和你的网络运营商、上网时段、VPS提供商关系很大，没有一个通用的优化参数，这个只能自己去调试。如果对参数配置有什么疑问的话，可以去[这里](https://github.com/xtaci/kcptun/issues)搜索或提问。
