### ISSUE TITLE
建议界面上加了小计算器

### ISSUE THREAD

**Issue by yjd** [dfdragon/kcptun_gclient#9]
官方有计算公式
-----------------------
在不丢包的情况下，有最大-rcvwnd 个数据包在网络上正在向你传输，以平均数据包大小avgsize计算，在任意时刻，有：     

        network_cap = rcvwnd*avgsize

数据流向你，这个值再除以ping值(rtt)，等于最大带宽使用量。

        max_bandwidth = network_cap/rtt = rcvwnd*avgsize/rtt

举例，设rcvwnd = 1024, avgsize = 1KB, rtt = 400ms，则：

        max_bandwidth = 1024 * 1KB / 400ms = 2.5MB/s ~= 25Mbps

（注：以上计算不包括前向纠错的数据量）

前向纠错是最大带宽量的一个固定比例增加：

        max_bandwidth_fec = max_bandwidth*(datashard+parityshard)/datashard

举例，设datashard = 10 , partiyshard = 3，则：

        max_bandwidth_fec = max_bandwidth * (10 + 3) /10 = 1.3*max_bandwidth ＝ 1.3 * 25Mbps = 32.5Mbps
---------------------
这样更方便了。找了几个win的客户端好像都没有。
目前kcptun_gclient做得比较方便统一都在一个窗口上配置比较人性化，赞。

**Comment by dfdragon** [comment]
这个功能应该用的不多吧，一般来说，根据你的网络情况做一到两次计算就可以了。参数可以参考[帖子](https://github.com/xtaci/kcptun/labels/PARAMS)

**Comment by yjd** [comment]
@dfdragon
写程序目的就是为了简化操作，提高效率。如果有个小窗口可以简单方便的输入几组数据就自动算出来。那将是非常省事。一个人少计算一次，nnn+个人一年下来就少计算多少次。
从编程上来说写这个属于体力活，如果太繁琐那就就不考虑了。
没学过delhpi没办法提交patch。
目前发现那个易版的有个简单输入带宽应该内部自动计算好 。
纯建议。开发者决定。

**Comment by dfdragon** [comment]
现在界面上可能不太好做了，我先考虑一下，感谢提议。

**Comment by yjd** [comment]
那几个参数中间中间放个显眼的小按钮(比如图标可以是一个计算器{直观}，也比如可以鼠标移过去就有气泡提示)，点完按钮弹出个小窗口用来计算的（更智能那就是点完计算结果自动写到对于空位^_^）。这样主界面就不用大调整。
辛苦了。

**Comment by hkyloveshe** [comment]
顺带提一个小小的建议吧，配置文件里路径那里默认存当前目录就好了，要不然到另外一个目录还要重新选择一下。

**Comment by dfdragon** [comment]
标准的opendialog好像不支持相对路径(这个我找找资料确认一下)。关于你的这个问题，解决方法也简单，打开kcptun.xml文件，将clientexedir的值由绝对路径改为相对路径就可以了，例如：.\client_windows_amd64.exe

hkyloveshe <notifications@github.com>于2016年11月28日周一 12:03写道：
